site_name: My Docs
site_url: https://tubuntu-full.github.io/mkdocs-repo4/
theme:
  name: material  # You can change this to 'readthedocs' if you prefer

nav:
  - Home: index.md
  - About: about.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - attr_list

plugins:
  - search
